### ISSUE TITLE
Demo link

### ISSUE THREAD

**Issue by ghost** [inlavigo/gg_router#4]
Hello,
In pub.dev you have a link to a demo, but just go to https://pub.dev/packages/gg_router#demo.
This is correct?
Shouldn't I go to the product demo? 
Regards,
Jose

**Comment by gatzsche** [comment]
Hi Jose, 

yea, thats a little bit misleading. It just points to a demo video. I'm going to change that. You can clone the project on GitHub and run the example contained in the code. 

Best, 
  Gabreil
