### ISSUE TITLE
gg-router is based on flutter navigator 2.0? 

### ISSUE THREAD

**Issue by ghost** [inlavigo/gg_router#5]
Hi Gabriel,
gg-router is based on flutter navigator 2.0 or do you use your own technology? 
I have been using Fluro for a project, but I was having trouble navigating between pages with the browser buttons.
For this reason I want to change the library for a new project. 
Another question, why in the change log the last version put that it is from July 14, 2021, but in the header of https://pub.dev/packages/gg_router it says that it is published on September 20, 2021? 
Thank you very much for the information. 
Regards, Jose

**Comment by gatzsche** [comment]
Under the hood gg-router is based on navigator 2.0. But it implements a fair different approach on the top of it. Did you look into the example? Is gg-router suitable for you? If not, what would be needed?

The inconsistency in the change log is a mistake.

**Comment by gatzsche** [comment]
Questions should be answered.
